#!/bin/sh


# Check for existing files and copy them
echo "Copying old files"
if [ -f ~/.vimrc ]; then
    cp ~/.vimrc ~/.vimrc_old
fi

if [ -f ~/.bash_profile ]; then
    cp ~/.bash_profile ~/.bash_profile
fi

if [ -f ~/.bash_aliases ]; then
    cp ~/.bash_aliases ~/.bash_aliases
fi

# Install the new config
echo "Installing new files"
cp vimrc ~/.vimrc
cp bash_profile ~/.bash_profile
cp bash_aliases ~/.bash_aliases

echo "done"
