#!/bin/sh


# Check for existing files and copy them
if [ -f ~/.vimrc ]; then
    cp ~/.vimrc ~/.vimrc_old
fi

if [ -f ~/.bash_profile ]; then
    cp ~/.bash_profile ~/.bash_profile
fi

# Install the new config
cp vimrc ~/.vimrc
cp bash_profile ~/.bash_profile
