#!/usr/bin/python
import sys
import colorsys

def main():
    code = makeCode(int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3]))
    sys.stdout.write(code)

def makeCode(r, g, b) :

    red_template = "\033]6;1;bg;red;brightness;%d\a"
    green_template = "\033]6;1;bg;green;brightness;%d\a"
    blue_template = "\033]6;1;bg;blue;brightness;%d\a"
    code = red_template % r + green_template % g + blue_template % b
    return code

main()
